services:
  # ---------- SQL Edge ----------
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Password@1 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 12

  # ---------- Redis ----------
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # ---------- RabbitMQ + UI ----------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  # ---------- ASP‑NET 8 ----------
  web:
    build:
      context: .
      dockerfile: src/UI/UI/Dockerfile
    container_name: booksy-web
    ports:
      - "9000:80"
      - "9001:443"
    depends_on:
      mssql:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=BooksyDb;User Id=SA;Password=Password@1;Encrypt=False;TrustServerCertificate=True;"

volumes:
  mssql_data:
  redis_data:
